// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddMovieController from "./add_movie_controller"
application.register("add-movie", AddMovieController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InfiniteScrollController from "./infinite_scroll_controller"
application.register("infinite-scroll", InfiniteScrollController)

import InsertInListController from "./insert_in_list_controller"
application.register("insert-in-list", InsertInListController)

import MarkFavoriteController from "./mark_favorite_controller"
application.register("mark-favorite", MarkFavoriteController)

import RefreshSearchController from "./refresh_search_controller"
application.register("refresh-search", RefreshSearchController)

import TreanoCarouselController from "./treano_carousel_controller"
application.register("treano-carousel", TreanoCarouselController)
